
// Types para el context de productos 

export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const OBTENER_PRODUCTOS_SUCCESS = 'OBTENER_PRODUCTOS_SUCCESS';
export const OBTENER_PRODUCTOS_ERROR = 'OBTENER_PRODUCTOS_ERROR';

export const OBTENER_PRODUCTO = 'OBTENER_PRODUCTO';
export const OBTENER_PRODUCTO_SUCCESS = 'OBTENER_PRODUCTO_SUCCESS';
export const OBTENER_PRODUCTO_ERROR = 'OBTENER_PRODUCTO_ERROR';


// Types para el context de carrito de compras 

export const MOSTRAR_CARRITO = 'MOSTRAR_CARRITO';
export const OCULTAR_CARRITO = 'OCULTAR_CARRITO';
export const AGREGAR_PRODUCTO_CARRITO = 'AGREGAR_PRODUCTO_CARRITO';
export const UPDATE_PRODUCTO_CARRITO = 'UPDATE_PRODUCTO_CARRITO';
export const ELIMINAR_PRODUCTO_CARRITO = 'ELIMINAR_PRODUCTO_CARRITO';